### ISSUE TITLE
QP-encoded sender/to gets misparsed

### ISSUE THREAD

**Issue by jengelh** [kisli/vmime#197]
```
Subject: blah
From: foo@bar.com
To: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>
MIME-Version: 1.0

testblorp
```
Observed behavior: `vmime::message::parse` turns the To line into `invalid@invalid`.
Expected behavior: `foo@bar.com`

```
#0  vmime::emailAddress::parseImpl (this=0x68a408, 
    buffer="=?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?=", position=0, end=50, newPosition=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/emailAddress.cpp:521
521                     m_localName = word("invalid", vmime::charsets::UTF_8);
(gdb) bt
#0  vmime::emailAddress::parseImpl (this=0x68a408, 
    buffer="=?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?=", position=0, end=50, newPosition=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/emailAddress.cpp:521
#1  0x00007ffff36bce7f in vmime::component::parse (this=0x68a408, ctx=..., 
    buffer="=?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?=")
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/component.cpp:107
#2  0x00007ffff36f83fa in vmime::mailbox::parseImpl (this=0x68a3c0, ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=38, end=102, newPosition=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/mailbox.cpp:324
#3  0x00007ffff36bcf66 in vmime::component::parse (this=0x68a3c0, ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=38, end=102, newPosition=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/component.cpp:128
#4  0x00007ffff368fa53 in vmime::address::parseNext (ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=38, end=102, 
    newPosition=0x7fffffffc348, isLastAddressOfGroup=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/address.cpp:206
#5  0x00007ffff3691950 in vmime::addressList::parseImpl (this=0x700600, ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=38, end=102, newPosition=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/addressList.cpp:63
#6  0x00007ffff36bcf66 in vmime::component::parse (this=0x700600, ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=38, end=102, newPosition=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/component.cpp:128
#7  0x00007ffff36e5bae in vmime::headerField::parseImpl (this=0x79d6a0, ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=38, end=102, newPosition=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/headerField.cpp:230
#8  0x00007ffff36bcf66 in vmime::component::parse (this=0x79d6a0, ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=38, end=102, newPosition=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/component.cpp:128
#9  0x00007ffff36e5820 in vmime::headerField::parseNext (ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=34, end=136, 
    newPosition=0x7fffffffc558) at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/headerField.cpp:179
#10 0x00007ffff36dea60 in vmime::header::parseImpl (this=0x76b7d0, ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <---Type <return> to continue, or q <return> to quit---
foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=0, end=136, newPosition=0x7fffffffc888)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/header.cpp:75
#11 0x00007ffff36bd0f6 in vmime::component::parseImpl (this=0x76b7d0, ctx=..., 
    parser=std::shared_ptr<vmime::utility::parserInputStreamAdapter> (use count 2, weak count 0) = {...}, position=0, end=136, newPosition=0x7fffffffc888)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/component.cpp:153
#12 0x00007ffff36bccca in vmime::component::parse (this=0x76b7d0, ctx=..., 
    inputStream=std::shared_ptr<vmime::utility::inputStream> (use count 5, weak count 0) = {...}, 
    position=0, end=136, newPosition=0x7fffffffc888)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/component.cpp:90
#13 0x00007ffff36aee34 in vmime::bodyPart::parseImpl (this=0x79d460, ctx=..., 
    parser=std::shared_ptr<vmime::utility::parserInputStreamAdapter> (use count 5, weak count 0) = {...}, position=0, end=136, newPosition=0x0) at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/bodyPart.cpp:46
#14 0x00007ffff36bd229 in vmime::component::parseImpl (this=0x79d460, ctx=..., 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n", position=0, end=136, newPosition=0x0)
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/component.cpp:177
#15 0x00007ffff36bce07 in vmime::component::parse (this=0x79d460, 
    buffer="Subject: blah\r\nFrom: foo@bar.com\r\nTo: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\nMIME-Version: 1.0\r\n\r\ntestblorp\r\n")
    at /usr/src/debug/libvmime-0.9.2-0.x86_64/src/vmime/component.cpp:99
```

**Comment by vincent-richard** [comment]
Hello!

With which version of VMime are you observing this?
I ran the following 3 tests with the git master, without any issue.

First one, with ```vmime::mailbox```:

```
vmime::mailbox mbox;
mbox.parse("=?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>");

VASSERT_EQ("mbox.name", "noble recipient (foo@bar.com)", mbox.getName().getWholeBuffer());
VASSERT_EQ("mbox.email", "foo@bar.com", mbox.getEmail());
```

Second one, with ```vmime::addressList```:

```
vmime::addressList addrList;
addrList.parse("=?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>");

vmime::shared_ptr <vmime::mailbox> mbox2 =
	vmime::dynamicCast <vmime::mailbox>(addrList.getAddressAt(0));

VASSERT("addrList.mbox", mbox2);
VASSERT_EQ("addrList.mbox.name", "noble recipient (foo@bar.com)", mbox2->getName().getWholeBuffer());
VASSERT_EQ("addrList.mbox.email", "foo@bar.com", mbox2->getEmail());
```

And last one, with ```vmime::message```:

```
vmime::message msg;
msg.parse(
"Subject: blah\r\n"
"From: foo@bar.com\r\n"
"To: =?UTF-8?Q?noble=c2=a0recipient_=28foo@bar.com=29?= <foo@bar.com>\r\n"
"MIME-Version: 1.0\r\n"
"\r\n"
"testblorp\r\n"
);

vmime::shared_ptr <vmime::addressList> addrList2 =
	vmime::dynamicCast <vmime::addressList>(msg.getHeader()->To());

vmime::shared_ptr <vmime::mailbox> mbox3 =
	vmime::dynamicCast <vmime::mailbox>(addrList.getAddressAt(0));

VASSERT("addrList2.mbox", mbox3);
VASSERT_EQ("addrList2.mbox.name", "noble recipient (foo@bar.com)", mbox3->getName().getWholeBuffer());
VASSERT_EQ("addrList2.mbox.email", "foo@bar.com", mbox3->getEmail());
```

**Comment by jengelh** [comment]
As specified, I was testing v0.9.2. Given you say it works in master, I bisected it down to b73d765f51f60475ddc2a8c1fca428a78a57d489, from which onwards it starts working. Didn't expect that, but ok.
Is it possible to get a new tag (0.9.3ish?) so that our software can check for the new behavior via just PKG_CHECK_MODULES?
